version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: frontdesk
      MYSQL_USER: frontdesk
      MYSQL_PASSWORD: frontdeskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=frontdesk
      - DATABASE_PASSWORD=frontdeskpass
      - DATABASE_NAME=frontdesk
      - JWT_SECRET=SuperSecretJWTKey
    ports:
      - "3001:3001"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
volumes:
  db_data:
